#############################################################################
# Makefile for building: QtPlugin
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sun Oct 9 13:10:34 2011
# Project:  QtPlugin.pro
# Template: subdirs
# Command: d:\qt\4.7.2\bin\qmake.exe -spec ..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o Makefile QtPlugin.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:\qt\4.7.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-app \
		sub-pluginloader \
		sub-utils

app\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) d:\workspace\QtPlugin\app\app.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-app-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) d:\workspace\QtPlugin\app\app.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-app: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE)
sub-app-make_default-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_default: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_first-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-make_first: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-all-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-all: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-clean-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-clean: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-distclean-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-distclean: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-install_subtargets-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-install_subtargets: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-uninstall_subtargets-ordered: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-app-uninstall_subtargets: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall
pluginloader\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) pluginloader\ $(MKDIR) pluginloader\ 
	cd pluginloader\ && $(QMAKE) d:\workspace\QtPlugin\pluginloader\pluginloader.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-pluginloader-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) pluginloader\ $(MKDIR) pluginloader\ 
	cd pluginloader\ && $(QMAKE) d:\workspace\QtPlugin\pluginloader\pluginloader.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-pluginloader: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE)
sub-pluginloader-make_default-ordered: pluginloader\$(MAKEFILE) sub-app-make_default-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) 
sub-pluginloader-make_default: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) 
sub-pluginloader-make_first-ordered: pluginloader\$(MAKEFILE) sub-app-make_first-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) first
sub-pluginloader-make_first: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) first
sub-pluginloader-all-ordered: pluginloader\$(MAKEFILE) sub-app-all-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) all
sub-pluginloader-all: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) all
sub-pluginloader-clean-ordered: pluginloader\$(MAKEFILE) sub-app-clean-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) clean
sub-pluginloader-clean: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) clean
sub-pluginloader-distclean-ordered: pluginloader\$(MAKEFILE) sub-app-distclean-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) distclean
sub-pluginloader-distclean: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) distclean
sub-pluginloader-install_subtargets-ordered: pluginloader\$(MAKEFILE) sub-app-install_subtargets-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) install
sub-pluginloader-install_subtargets: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) install
sub-pluginloader-uninstall_subtargets-ordered: pluginloader\$(MAKEFILE) sub-app-uninstall_subtargets-ordered  FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-pluginloader-uninstall_subtargets: pluginloader\$(MAKEFILE) FORCE
	cd pluginloader\ && $(MAKE) -f $(MAKEFILE) uninstall
utils\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) utils\ $(MKDIR) utils\ 
	cd utils\ && $(QMAKE) d:\workspace\QtPlugin\utils\utils.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-utils-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) utils\ $(MKDIR) utils\ 
	cd utils\ && $(QMAKE) d:\workspace\QtPlugin\utils\utils.pro -spec ..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o $(MAKEFILE)
sub-utils: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE)
sub-utils-make_default-ordered: utils\$(MAKEFILE) sub-pluginloader-make_default-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) 
sub-utils-make_default: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) 
sub-utils-make_first-ordered: utils\$(MAKEFILE) sub-pluginloader-make_first-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) first
sub-utils-make_first: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) first
sub-utils-all-ordered: utils\$(MAKEFILE) sub-pluginloader-all-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) all
sub-utils-all: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) all
sub-utils-clean-ordered: utils\$(MAKEFILE) sub-pluginloader-clean-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) clean
sub-utils-clean: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) clean
sub-utils-distclean-ordered: utils\$(MAKEFILE) sub-pluginloader-distclean-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) distclean
sub-utils-distclean: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) distclean
sub-utils-install_subtargets-ordered: utils\$(MAKEFILE) sub-pluginloader-install_subtargets-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) install
sub-utils-install_subtargets: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) install
sub-utils-uninstall_subtargets-ordered: utils\$(MAKEFILE) sub-pluginloader-uninstall_subtargets-ordered  FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-utils-uninstall_subtargets: utils\$(MAKEFILE) FORCE
	cd utils\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: QtPlugin.pro  ..\..\Qt\4.7.2\mkspecs\win32-msvc2008\qmake.conf ..\..\Qt\4.7.2\mkspecs\qconfig.pri \
		..\..\Qt\4.7.2\mkspecs\modules\qt_webkit_version.pri \
		..\..\Qt\4.7.2\mkspecs\features\qt_functions.prf \
		..\..\Qt\4.7.2\mkspecs\features\qt_config.prf \
		..\..\Qt\4.7.2\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\4.7.2\mkspecs\features\default_pre.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\default_pre.prf \
		..\..\Qt\4.7.2\mkspecs\features\debug.prf \
		..\..\Qt\4.7.2\mkspecs\features\debug_and_release.prf \
		..\..\Qt\4.7.2\mkspecs\features\default_post.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\default_post.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\rtti.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\exceptions.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\stl.prf \
		..\..\Qt\4.7.2\mkspecs\features\shared.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\Qt\4.7.2\mkspecs\features\warn_on.prf \
		..\..\Qt\4.7.2\mkspecs\features\qt.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\thread.prf \
		..\..\Qt\4.7.2\mkspecs\features\moc.prf \
		..\..\Qt\4.7.2\mkspecs\features\win32\windows.prf \
		..\..\Qt\4.7.2\mkspecs\features\resources.prf \
		..\..\Qt\4.7.2\mkspecs\features\uic.prf \
		..\..\Qt\4.7.2\mkspecs\features\yacc.prf \
		..\..\Qt\4.7.2\mkspecs\features\lex.prf \
		..\..\Qt\4.7.2\mkspecs\features\incredibuild_xge.prf \
		..\..\Qt\4.7.2\mkspecs\features\include_source_dir.prf
	$(QMAKE) -spec ..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o Makefile QtPlugin.pro
..\..\Qt\4.7.2\mkspecs\qconfig.pri:
..\..\Qt\4.7.2\mkspecs\modules\qt_webkit_version.pri:
..\..\Qt\4.7.2\mkspecs\features\qt_functions.prf:
..\..\Qt\4.7.2\mkspecs\features\qt_config.prf:
..\..\Qt\4.7.2\mkspecs\features\exclusive_builds.prf:
..\..\Qt\4.7.2\mkspecs\features\default_pre.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\default_pre.prf:
..\..\Qt\4.7.2\mkspecs\features\debug.prf:
..\..\Qt\4.7.2\mkspecs\features\debug_and_release.prf:
..\..\Qt\4.7.2\mkspecs\features\default_post.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\default_post.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\rtti.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\exceptions.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\stl.prf:
..\..\Qt\4.7.2\mkspecs\features\shared.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\Qt\4.7.2\mkspecs\features\warn_on.prf:
..\..\Qt\4.7.2\mkspecs\features\qt.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\thread.prf:
..\..\Qt\4.7.2\mkspecs\features\moc.prf:
..\..\Qt\4.7.2\mkspecs\features\win32\windows.prf:
..\..\Qt\4.7.2\mkspecs\features\resources.prf:
..\..\Qt\4.7.2\mkspecs\features\uic.prf:
..\..\Qt\4.7.2\mkspecs\features\yacc.prf:
..\..\Qt\4.7.2\mkspecs\features\lex.prf:
..\..\Qt\4.7.2\mkspecs\features\incredibuild_xge.prf:
..\..\Qt\4.7.2\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\Qt\4.7.2\mkspecs\win32-msvc2008 QMLJSDEBUGGER_PATH=d:/Qt/4.7.2/qtc-qmldbg -o Makefile QtPlugin.pro

qmake_all: sub-app-qmake_all sub-pluginloader-qmake_all sub-utils-qmake_all FORCE

make_default: sub-app-make_default-ordered sub-pluginloader-make_default-ordered sub-utils-make_default-ordered FORCE
make_first: sub-app-make_first-ordered sub-pluginloader-make_first-ordered sub-utils-make_first-ordered FORCE
all: sub-app-all-ordered sub-pluginloader-all-ordered sub-utils-all-ordered FORCE
clean: sub-app-clean-ordered sub-pluginloader-clean-ordered sub-utils-clean-ordered FORCE
distclean: sub-app-distclean-ordered sub-pluginloader-distclean-ordered sub-utils-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-app-install_subtargets-ordered sub-pluginloader-install_subtargets-ordered sub-utils-install_subtargets-ordered FORCE
uninstall_subtargets: sub-app-uninstall_subtargets-ordered sub-pluginloader-uninstall_subtargets-ordered sub-utils-uninstall_subtargets-ordered FORCE

sub-app-sub_Debug_ordered: app\$(MAKEFILE)
	cd app\ && $(MAKE) debug
sub-pluginloader-sub_Debug_ordered: pluginloader\$(MAKEFILE) sub-app-sub_Debug_ordered 
	cd pluginloader\ && $(MAKE) debug
sub-utils-sub_Debug_ordered: utils\$(MAKEFILE) sub-pluginloader-sub_Debug_ordered 
	cd utils\ && $(MAKE) debug
debug: sub-app-sub_Debug_ordered sub-pluginloader-sub_Debug_ordered sub-utils-sub_Debug_ordered

sub-app-sub_Release_ordered: app\$(MAKEFILE)
	cd app\ && $(MAKE) release
sub-pluginloader-sub_Release_ordered: pluginloader\$(MAKEFILE) sub-app-sub_Release_ordered 
	cd pluginloader\ && $(MAKE) release
sub-utils-sub_Release_ordered: utils\$(MAKEFILE) sub-pluginloader-sub_Release_ordered 
	cd utils\ && $(MAKE) release
release: sub-app-sub_Release_ordered sub-pluginloader-sub_Release_ordered sub-utils-sub_Release_ordered

sub-app-check_ordered: app\$(MAKEFILE)
	cd app\ && $(MAKE) check
sub-pluginloader-check_ordered: pluginloader\$(MAKEFILE) sub-app-check_ordered 
	cd pluginloader\ && $(MAKE) check
sub-utils-check_ordered: utils\$(MAKEFILE) sub-pluginloader-check_ordered 
	cd utils\ && $(MAKE) check
check: sub-app-check_ordered sub-pluginloader-check_ordered sub-utils-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

